#+TITLE: A Python parser for Org Mode nodes
#+ARCHIVE: ./docs/plans/ROADMAP_ARCHIVE.org::

* Initial release
** DONE Supported syntax in the README.org
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-03-22 Sun 00:09]
:END:
Please expand the README.org file with examples of all the features supported by the parser. It should list all the supported features in the =Supported features= heading as subheadings.

Each features should have a clear example embedded within the file itself and a description of whether it is supported in Tree-Sitter grammar or just in Python wrapper and via what means (node names, module names etc).
Keep the examples short and instrumental, focused on just a single feature.
Keep the descriptions short and focused.

You can combine multiple related features into a single subheading (for instance, all inline markup objects can be a single subheading, various lists, etc). Here's an example:

#+begin_example
,** Inline markup
_This_ /parser/ *supports* =the= ~following~ +inline+ markup^{objects}.

All of the above are supported in the Tree-Sitter grammar as well as in the Python wrapper.
#+end_example

** DONE Use external tree-sitter-org grammar
:LOGBOOK:
- State "DONE"       from              [2026-03-28 Sat 17:48]
:END:
** Automated tests based on the example files.
** Semantic node documentation
** Library release
