#+TITLE: A Python parser for Org Mode documents
#+ARCHIVE: ./docs/plans/ROADMAP_ARCHIVE.org::

* Bugfixes
** DONE Well-formed, but rejected repeats
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-06 Mon 14:53]
:END:

#+begin_example
,** Test
   :LOGBOOK:
   - State              from              [2023-07-13 czw 10:32]
   - State ""           from ""           [2023-07-13 czw 10:32]
   - State              from "TODO"       [2022-07-10 Sun 22:58]
   - State ""           from "TODO"       [2021-07-13 Tue 18:53]
   - State "DONE"       from ""           [2013-07-09 wto 22:58]
   - State "DONE"       from "TODO"       [2012-07-10 wto 20:05]
   :END:
#+end_example

All of the above should parse as repeats - the empty values (~""~) should become =None=, same for missing values.

** TODO Setting repeats when only using body-repeats does not remove them from the body.
#+begin_example
,* DONE Test
   - State "DONE"       from "ACTIVE"     [2012-10-05 pią 19:49]
   - State "ACTIVE"     from "BLOCKER"    [2012-10-03 śro 09:37]
   - State "BLOCKER"    from "BLOCKER"    [2012-09-19 śro 17:55]
#+end_example

Given the above task, setting the repeats does not affect the list in the body.

* Features
** TODO =to_json()= convenience method
All objects should be convertible to "simple" JSON objects:
- =RichText= should be represented by its string representation value,
- All other objects should become JSON objects with a =type= field indicating the class-name of the underlying object and an attribute for each of the writable attributes of the object.

Omit the =children=, =siblings=, =parent=, =all_heading= and any other fields that could lead to a recursive conversion.
Prefer =body= and =title= to =body_text= and =title_text=, etc.
