#+TITLE: A Python parser for Org Mode documents
#+ARCHIVE: ./docs/plans/ROADMAP_ARCHIVE.org::

* Bugfixes
** DONE Bump tree-sitter-org to 0.23.7
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-05 Sun 17:51]
:END:

** DONE =ListItem= representation omits the counter
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-05 Sun 17:59]
:END:
Ordered list representation omits the counter (and likely other fileds), it only presents the bullet (which isn't useful by itself). Please ensure that list item's =__repr__= shows all non-None fields.

* Additions
** DONE =RichText.trimmed=
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-05 Sun 19:08]
:END:
Add a new read-only attribute to the =RichText= class that returns a new =RichText= object that has any leading or trailing whitespace removed.

** DONE =RichText.stripped=
:LOGBOOK:
- State "DONE"       from "TODO"       [2026-04-05 Sun 19:21]
:END:
Add a new read-only attribute to the =RichText= class that returns a new =RichText= object that has inline markup stripped according to the following rules:
- Bold, italic, underline etc markup is replaced with the raw body without the markup. Take special care for nested markup.
- Links, cites and footnotes with a description are replaced with the description.
- Links, cites and footnotes without a description are replaced with the link value (without the brackets).
- All other inline objects including Timestamps are replaced with their textual representation.

The goal is for the =stripped= attribute to be a visual representation of a string of =RichText= without the markup. Essentially, =stripped= rich text will consist mostly of plaintext objects.

** TODO =to_json()= convenience method
All objects should be convertible to "simple" JSON objects:
- =RichText= should be represented by its string representation value,
- All other objects should become JSON objects with a =type= field indicating the class-name of the underlying object and an attribute for each of the writable attributes of the object.

Omit the =children=, =siblings=, =parent=, =all_heading= and any other fields that could lead to a recursive conversion.
Prefer =body= and =title= to =body_text= and =title_text=, etc.

** TODO =Properties= values to accept any type
It should be possible to set any property to any type. These values should be aucomatically stringified for dirty rendering, but otherwise accessible as-is. I.e.:

#+begin_example
>>> node.properties["foo"] = 23
>>> node.properties["foo"] * 2
46
>>> print(str(node.properties))
:PROPERTIES:
:foo: 23
:END:
#+end_example

** TODO =Repeat.is_completed= convenience attribute
Add a convenience field to =Repeat= that indicaties if the =after= property is in the =parent.document.done_states=. Its semantics should be the same as =Heading.is_completed=.
